// app/ui/components/DownChevron.tsx
'use client';


import "@/app/ui/DownChevron.css";
import Image from "next/image";
import { useEffect, useRef } from "react";
import { animate } from "animejs";


export default () => {
    // const chevronContainer = useRef<HTMLDivElement | null>(null);

    useEffect(() => {
        // animate(chevronContainer.current, {
        animate("#down-chevron-container", {
            bottom: "+=7px",
            loop: true,
            alternate: true,
            easing: "inQuad",
            duration: 600
        });
    }, []);


    return (
        // <div id="down-chevron-container" ref={chevronContainer}>
        <div id="down-chevron-container">
            <Image
                src={"/icon/downchevron.svg"}
                alt={"Down arrow"}
                width={80}
                height={80}/>

            {/*<svg xmlns="http://www.w3.org/2000/svg"*/}
            {/*     width="80"*/}
            {/*     height="80"*/}
            {/*     viewBox="0 0 24 24"*/}
            {/*     fill="none"*/}
            {/*     stroke="currentColor"*/}
            {/*     stroke-width="0.5"*/}
            {/*     stroke-linecap="round"*/}
            {/*     stroke-linejoin="round"*/}
            {/*     className="feather feather-chevron-down">*/}
            {/*    <polyline points="6 9 12 15 18 9"/>*/}
            {/*</svg>*/}
        </div>
    );
}

// src/components/DownChevron.vue
<script setup>
import { animate, splitText, stagger, random } from 'animejs';
import { onMounted } from "vue";

onMounted(() => {
    animate("#down-chevron-container", {
        bottom: "+=7px",
        loop: true,
        alternate: true,
        easing: "inQuad",
        duration: 600
    });
});
</script>



<template>
    <div id="down-chevron-container">
        <svg xmlns="http://www.w3.org/2000/svg"
            width="80"
            height="80"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="0.5"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="feather feather-chevron-down">
            <polyline points="6 9 12 15 18 9" />
        </svg>
    </div>
</template>




<style lang="scss" scoped>
@use "../css/partials/_colors.scss" as *;

#down-chevron-container {
    width: 45px;
    position: absolute;
    bottom: 20px;
    display: flex;
    place-content: center;

    svg {
        color: $color-light-2;
        min-width: 100%;
        height: min-content;
    }
}
</style>
